# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 18:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='first_day',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 18, 12, 6, 80034, tzinfo=utc)),
        ),
    ]
