# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 16:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_remove_animal_from_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='days_in_adoption',
        ),
        migrations.AddField(
            model_name='animal',
            name='first_day',
            field=models.DateField(default=datetime.datetime(2017, 11, 18, 16, 46, 12, 663288, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='animal',
            name='color',
            field=models.IntegerField(choices=[(1, 'marron'), (2, 'amarillo'), (3, 'blanco'), (4, 'gris'), (5, 'manchado')]),
        ),
    ]
