# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0006_auto_20171023_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='color',
            field=models.TextField(choices=[(1, 'Reportada'), (2, 'Consolidada'), (3, 'Verificada'), (4, 'Cerrada'), (5, 'Desechada')]),
        ),
    ]
