# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0007_auto_20171117_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='color',
            field=models.TextField(choices=[(1, 'marron'), (2, 'amarillo'), (3, 'blanco'), (4, 'gris'), (5, 'manchado')]),
        ),
    ]
